export const departments = [
    {
        name: "Computer Science & Engineering",
        code: "CSE",
        website: "https://cse.university.edu",
    },
    {
        name: "Electrical Engineering",
        code: "EE",
        website: "https://ee.university.edu",
    },
    {
        name: "Mechanical Engineering",
        code: "ME",
        website: "https://me.university.edu",
    },
    {
        name: "Civil Engineering",
        code: "CE",
        website: "https://ce.university.edu",
    },
    {
        name: "Electronics & Communication",
        code: "ECE",
        website: "https://ece.university.edu",
    },
];

export const hods = [
    {
        name: "Dr. Rajesh Kumar",
        email: "2023csb1153+h1@iitrpr.ac.in",
        phoneNumber: "+919876543210",
        website: "https://rajesh-kumar.edu",
        employeeId: "+h1",
        deptCode: "CSE",
    },
    {
        name: "Dr. Priya Sharma",
        email: "2023csb1161+h2@iitrpr.ac.in",
        phoneNumber: "+919876543211",
        website: "https://priya-sharma.edu",
        employeeId: "+h2",
        deptCode: "EE",
    },
    {
        name: "Dr. Amit Patel",
        email: "2023csb1153+h3@iitrpr.ac.in",
        phoneNumber: "+919876543212",
        website: "https://amit-patel.edu",
        employeeId: "+h3",
        deptCode: "ME",
    },
    {
        name: "Dr. Sunita Verma",
        email: "2023csb1161+h4@iitrpr.ac.in",
        phoneNumber: "+919876543213",
        website: "https://sunita-verma.edu",
        employeeId: "+h4",
        deptCode: "CE",
    },
    {
        name: "Dr. Vikram Singh",
        email: "2023csb1153+h5@iitrpr.ac.in",
        phoneNumber: "+919876543214",
        website: "https://vikram-singh.edu",
        employeeId: "+h5",
        deptCode: "ECE",
    },
];

export const programs = [
    {
        name: "Bachelor of Technology in Computer Science",
        code: "BTCS",
        degreeType: "BACHELOR" as const,
        deptCode: "CSE",
    },
    {
        name: "Master of Technology in Computer Science",
        code: "MTCS",
        degreeType: "MASTER" as const,
        deptCode: "CSE",
    },
    {
        name: "Bachelor of Technology in Electrical Engineering",
        code: "BTEE",
        degreeType: "BACHELOR" as const,
        deptCode: "EE",
    },
    {
        name: "Master of Technology in Electrical Engineering",
        code: "MTEE",
        degreeType: "MASTER" as const,
        deptCode: "EE",
    },
    {
        name: "Bachelor of Technology in Mechanical Engineering",
        code: "BTME",
        degreeType: "BACHELOR" as const,
        deptCode: "ME",
    },
    {
        name: "Doctor of Philosophy in Computer Science",
        code: "PHCS",
        degreeType: "PHD" as const,
        deptCode: "CSE",
    },
];

export const advisors = [
    {
        name: "Dr. Anita Desai",
        email: "2023csb1153+a1@iitrpr.ac.in",
        phoneNumber: "+919876543220",
        website: "https://anita-desai.edu",
        employeeId: "+a1",
        deptCode: "CSE",
    },
    {
        name: "Dr. Rahul Mehta",
        email: "2023csb1161+a2@iitrpr.ac.in",
        phoneNumber: "+919876543221",
        website: "https://rahul-mehta.edu",
        employeeId: "+a2",
        deptCode: "CSE",
    },
    {
        name: "Dr. Kavita Reddy",
        email: "2023csb1153+a3@iitrpr.ac.in",
        phoneNumber: "+919876543222",
        website: "https://kavita-reddy.edu",
        employeeId: "+a3",
        deptCode: "EE",
    },
    {
        name: "Dr. Sanjay Gupta",
        email: "2023csb1161+a4@iitrpr.ac.in",
        phoneNumber: "+919876543223",
        website: "https://sanjay-gupta.edu",
        employeeId: "+a4",
        deptCode: "EE",
    },
    {
        name: "Dr. Neha Joshi",
        email: "2023csb1153+a5@iitrpr.ac.in",
        phoneNumber: "+919876543224",
        website: "https://neha-joshi.edu",
        employeeId: "+a5",
        deptCode: "ME",
    },
    {
        name: "Dr. Arun Kumar",
        email: "2023csb1161+a6@iitrpr.ac.in",
        phoneNumber: "+919876543225",
        website: "https://arun-kumar.edu",
        employeeId: "+a6",
        deptCode: "CE",
    },
    {
        name: "Dr. Pooja Iyer",
        email: "2023csb1153+a7@iitrpr.ac.in",
        phoneNumber: "+919876543226",
        website: "https://pooja-iyer.edu",
        employeeId: "+a7",
        deptCode: "ECE",
    },
];

export const instructors = [
    {
        name: "Prof. Deepak Chopra",
        email: "2023csb1153+i1@iitrpr.ac.in",
        phoneNumber: "+919876543230",
        website: "https://deepak-chopra.edu",
        employeeId: "+i1",
        deptCode: "CSE",
        designation: "Associate Professor",
    },
    {
        name: "Prof. Meera Nair",
        email: "2023csb1161+i2@iitrpr.ac.in",
        phoneNumber: "+919876543231",
        website: "https://meera-nair.edu",
        employeeId: "+i2",
        deptCode: "CSE",
        designation: "Assistant Professor",
    },
    {
        name: "Prof. Kiran Rao",
        email: "2023csb1153+i3@iitrpr.ac.in",
        phoneNumber: "+919876543232",
        website: "https://kiran-rao.edu",
        employeeId: "+i3",
        deptCode: "CSE",
        designation: "Professor",
    },
    {
        name: "Prof. Suresh Pillai",
        email: "2023csb1161+i4@iitrpr.ac.in",
        phoneNumber: "+919876543233",
        website: "https://suresh-pillai.edu",
        employeeId: "+i4",
        deptCode: "EE",
        designation: "Associate Professor",
    },
    {
        name: "Prof. Lakshmi Menon",
        email: "2023csb1153+i5@iitrpr.ac.in",
        phoneNumber: "+919876543234",
        website: "https://lakshmi-menon.edu",
        employeeId: "+i5",
        deptCode: "EE",
        designation: "Assistant Professor",
    },
    {
        name: "Prof. Ravi Shankar",
        email: "2023csb1161+i6@iitrpr.ac.in",
        phoneNumber: "+919876543235",
        website: "https://ravi-shankar.edu",
        employeeId: "+i6",
        deptCode: "ME",
        designation: "Professor",
    },
    {
        name: "Prof. Gita Krishnan",
        email: "2023csb1153+i7@iitrpr.ac.in",
        phoneNumber: "+919876543236",
        website: "https://gita-krishnan.edu",
        employeeId: "+i7",
        deptCode: "ME",
        designation: "Assistant Professor",
    },
    {
        name: "Prof. Manoj Tiwari",
        email: "2023csb1161+i8@iitrpr.ac.in",
        phoneNumber: "+919876543237",
        website: "https://manoj-tiwari.edu",
        employeeId: "+i8",
        deptCode: "CE",
        designation: "Associate Professor",
    },
    {
        name: "Prof. Shweta Agarwal",
        email: "2023csb1153+i9@iitrpr.ac.in",
        phoneNumber: "+919876543238",
        website: "https://shweta-agarwal.edu",
        employeeId: "+i9",
        deptCode: "ECE",
        designation: "Professor",
    },
    {
        name: "Prof. Vijay Malhotra",
        email: "2023csb1161+i10@iitrpr.ac.in",
        phoneNumber: "+919876543239",
        website: "https://vijay-malhotra.edu",
        employeeId: "+i10",
        deptCode: "ECE",
        designation: "Assistant Professor",
    },
];

export const students = [
    {
        name: "Arjun Patel",
        email: "2023csb1153+s1@iitrpr.ac.in",
        rollNo: "2021CSE001",
        programCode: "BTCS",
        batchYear: 2021,
        advisorEmployeeId: "+a1",
    },
    {
        name: "Priya Singh",
        email: "2023csb1161+s2@iitrpr.ac.in",
        rollNo: "2021CSE002",
        programCode: "BTCS",
        batchYear: 2021,
        advisorEmployeeId: "+a1",
    },
    {
        name: "Rohan Kumar",
        email: "2023csb1153+s3@iitrpr.ac.in",
        rollNo: "2021CSE003",
        programCode: "BTCS",
        batchYear: 2021,
        advisorEmployeeId: "+a2",
    },
    {
        name: "Sneha Sharma",
        email: "2023csb1161+s4@iitrpr.ac.in",
        rollNo: "2021CSE004",
        programCode: "BTCS",
        batchYear: 2021,
        advisorEmployeeId: "+a2",
    },
    {
        name: "Amit Verma",
        email: "2023csb1153+s5@iitrpr.ac.in",
        rollNo: "2022CSE001",
        programCode: "BTCS",
        batchYear: 2022,
        advisorEmployeeId: "+a1",
    },
    {
        name: "Neha Reddy",
        email: "2023csb1161+s6@iitrpr.ac.in",
        rollNo: "2022CSE002",
        programCode: "BTCS",
        batchYear: 2022,
        advisorEmployeeId: "+a2",
    },
    {
        name: "Karan Mehta",
        email: "2023csb1153+s7@iitrpr.ac.in",
        rollNo: "2023CSE001",
        programCode: "BTCS",
        batchYear: 2023,
        advisorEmployeeId: "+a1",
    },
    {
        name: "Divya Gupta",
        email: "2023csb1161+s8@iitrpr.ac.in",
        rollNo: "2023CSE002",
        programCode: "BTCS",
        batchYear: 2023,
        advisorEmployeeId: "+a2",
    },
    {
        name: "Rahul Joshi",
        email: "2023csb1153+s9@iitrpr.ac.in",
        rollNo: "2021EE001",
        programCode: "BTEE",
        batchYear: 2021,
        advisorEmployeeId: "+a3",
    },
    {
        name: "Kavya Iyer",
        email: "2023csb1161+s10@iitrpr.ac.in",
        rollNo: "2021EE002",
        programCode: "BTEE",
        batchYear: 2021,
        advisorEmployeeId: "+a4",
    },
    {
        name: "Siddharth Nair",
        email: "2023csb1153+s11@iitrpr.ac.in",
        rollNo: "2022EE001",
        programCode: "BTEE",
        batchYear: 2022,
        advisorEmployeeId: "+a3",
    },
    {
        name: "Anjali Rao",
        email: "2023csb1161+s12@iitrpr.ac.in",
        rollNo: "2022EE002",
        programCode: "BTEE",
        batchYear: 2022,
        advisorEmployeeId: "+a4",
    },
    {
        name: "Varun Pillai",
        email: "2023csb1153+s13@iitrpr.ac.in",
        rollNo: "2023EE001",
        programCode: "BTEE",
        batchYear: 2023,
        advisorEmployeeId: "+a3",
    },
    {
        name: "Riya Menon",
        email: "2023csb1161+s14@iitrpr.ac.in",
        rollNo: "2023EE002",
        programCode: "BTEE",
        batchYear: 2023,
        advisorEmployeeId: "+a4",
    },
    {
        name: "Aditya Kumar",
        email: "2023csb1153+s15@iitrpr.ac.in",
        rollNo: "2021ME001",
        programCode: "BTME",
        batchYear: 2021,
        advisorEmployeeId: "+a5",
    },
    {
        name: "Simran Singh",
        email: "2023csb1161+s16@iitrpr.ac.in",
        rollNo: "2021ME002",
        programCode: "BTME",
        batchYear: 2021,
        advisorEmployeeId: "+a5",
    },
    {
        name: "Akash Sharma",
        email: "2023csb1153+s17@iitrpr.ac.in",
        rollNo: "2022ME001",
        programCode: "BTME",
        batchYear: 2022,
        advisorEmployeeId: "+a5",
    },
    {
        name: "Pooja Patel",
        email: "2023csb1161+s18@iitrpr.ac.in",
        rollNo: "2022ME002",
        programCode: "BTME",
        batchYear: 2022,
        advisorEmployeeId: "+a5",
    },
    {
        name: "Nikhil Verma",
        email: "2023csb1153+s19@iitrpr.ac.in",
        rollNo: "2023ME001",
        programCode: "BTME",
        batchYear: 2023,
        advisorEmployeeId: "+a5",
    },
    {
        name: "Ishita Reddy",
        email: "2023csb1161+s20@iitrpr.ac.in",
        rollNo: "2023ME002",
        programCode: "BTME",
        batchYear: 2023,
        advisorEmployeeId: "+a5",
    },
    {
        name: "Manish Gupta",
        email: "2023csb1153+s21@iitrpr.ac.in",
        rollNo: "2022CSE003",
        programCode: "BTCS",
        batchYear: 2022,
        advisorEmployeeId: "+a1",
    },
    {
        name: "Shruti Joshi",
        email: "2023csb1161+s22@iitrpr.ac.in",
        rollNo: "2022CSE004",
        programCode: "BTCS",
        batchYear: 2022,
        advisorEmployeeId: "+a2",
    },
    {
        name: "Harsh Iyer",
        email: "2023csb1153+s23@iitrpr.ac.in",
        rollNo: "2023CSE003",
        programCode: "BTCS",
        batchYear: 2023,
        advisorEmployeeId: "+a1",
    },
    {
        name: "Tanvi Nair",
        email: "2023csb1161+s24@iitrpr.ac.in",
        rollNo: "2023CSE004",
        programCode: "BTCS",
        batchYear: 2023,
        advisorEmployeeId: "+a2",
    },
    {
        name: "Vishal Rao",
        email: "2023csb1153+s25@iitrpr.ac.in",
        rollNo: "2021CSE005",
        programCode: "BTCS",
        batchYear: 2021,
        advisorEmployeeId: "+a1",
    },
    {
        name: "Megha Pillai",
        email: "2023csb1161+s26@iitrpr.ac.in",
        rollNo: "2021CSE006",
        programCode: "BTCS",
        batchYear: 2021,
        advisorEmployeeId: "+a2",
    },
    {
        name: "Shubham Menon",
        email: "2023csb1153+s27@iitrpr.ac.in",
        rollNo: "2022EE003",
        programCode: "BTEE",
        batchYear: 2022,
        advisorEmployeeId: "+a3",
    },
    {
        name: "Ananya Kumar",
        email: "2023csb1161+s28@iitrpr.ac.in",
        rollNo: "2022EE004",
        programCode: "BTEE",
        batchYear: 2022,
        advisorEmployeeId: "+a4",
    },
    {
        name: "Yash Singh",
        email: "2023csb1153+s29@iitrpr.ac.in",
        rollNo: "2023ME003",
        programCode: "BTME",
        batchYear: 2023,
        advisorEmployeeId: "+a5",
    },
    {
        name: "Kriti Sharma",
        email: "2023csb1161+s30@iitrpr.ac.in",
        rollNo: "2023ME004",
        programCode: "BTME",
        batchYear: 2023,
        advisorEmployeeId: "+a5",
    },
];

export const courses = [
    {
        code: "CS101",
        title: "Introduction to Programming",
        lectureHours: 3,
        tutorialHours: 1,
        practicalHours: 2,
        selfStudyHours: 4,
        credits: 4,
        deptCode: "CSE",
        description: {
            objectives: ["Learn basic programming"],
            outcomes: ["Write simple programs"],
        },
    },
    {
        code: "CS201",
        title: "Data Structures",
        lectureHours: 3,
        tutorialHours: 1,
        practicalHours: 2,
        selfStudyHours: 4,
        credits: 4,
        deptCode: "CSE",
        description: {
            objectives: ["Learn data structures"],
            outcomes: ["Implement DS"],
        },
    },
    {
        code: "CS301",
        title: "Algorithms",
        lectureHours: 3,
        tutorialHours: 1,
        practicalHours: 0,
        selfStudyHours: 6,
        credits: 3,
        deptCode: "CSE",
        description: {
            objectives: ["Learn algorithms"],
            outcomes: ["Analyze algorithms"],
        },
    },
    {
        code: "CS401",
        title: "Database Systems",
        lectureHours: 3,
        tutorialHours: 0,
        practicalHours: 2,
        selfStudyHours: 5,
        credits: 3.5,
        deptCode: "CSE",
        description: {
            objectives: ["Learn DBMS"],
            outcomes: ["Design databases"],
        },
    },
    {
        code: "CS501",
        title: "Machine Learning",
        lectureHours: 3,
        tutorialHours: 1,
        practicalHours: 2,
        selfStudyHours: 4,
        credits: 4,
        deptCode: "CSE",
        description: {
            objectives: ["Learn ML"],
            outcomes: ["Build ML models"],
        },
    },
    {
        code: "EE101",
        title: "Basic Electrical Engineering",
        lectureHours: 3,
        tutorialHours: 1,
        practicalHours: 2,
        selfStudyHours: 4,
        credits: 4,
        deptCode: "EE",
        description: {
            objectives: ["Learn EE basics"],
            outcomes: ["Understand circuits"],
        },
    },
    {
        code: "EE201",
        title: "Circuit Analysis",
        lectureHours: 3,
        tutorialHours: 1,
        practicalHours: 0,
        selfStudyHours: 6,
        credits: 3,
        deptCode: "EE",
        description: {
            objectives: ["Analyze circuits"],
            outcomes: ["Solve circuit problems"],
        },
    },
    {
        code: "EE301",
        title: "Digital Electronics",
        lectureHours: 3,
        tutorialHours: 0,
        practicalHours: 2,
        selfStudyHours: 5,
        credits: 3.5,
        deptCode: "EE",
        description: {
            objectives: ["Learn digital systems"],
            outcomes: ["Design digital circuits"],
        },
    },
    {
        code: "EE401",
        title: "Power Systems",
        lectureHours: 3,
        tutorialHours: 1,
        practicalHours: 2,
        selfStudyHours: 4,
        credits: 4,
        deptCode: "EE",
        description: {
            objectives: ["Learn power systems"],
            outcomes: ["Analyze power grids"],
        },
    },
    {
        code: "ME101",
        title: "Engineering Mechanics",
        lectureHours: 3,
        tutorialHours: 1,
        practicalHours: 2,
        selfStudyHours: 4,
        credits: 4,
        deptCode: "ME",
        description: {
            objectives: ["Learn mechanics"],
            outcomes: ["Apply mechanics"],
        },
    },
    {
        code: "ME201",
        title: "Thermodynamics",
        lectureHours: 3,
        tutorialHours: 1,
        practicalHours: 0,
        selfStudyHours: 6,
        credits: 3,
        deptCode: "ME",
        description: {
            objectives: ["Learn thermodynamics"],
            outcomes: ["Solve thermo problems"],
        },
    },
    {
        code: "ME301",
        title: "Fluid Mechanics",
        lectureHours: 3,
        tutorialHours: 0,
        practicalHours: 2,
        selfStudyHours: 5,
        credits: 3.5,
        deptCode: "ME",
        description: {
            objectives: ["Learn fluid mechanics"],
            outcomes: ["Analyze fluid flow"],
        },
    },
    {
        code: "MATH101",
        title: "Calculus I",
        lectureHours: 4,
        tutorialHours: 1,
        practicalHours: 0,
        selfStudyHours: 5,
        credits: 4,
        deptCode: "CSE",
        description: {
            objectives: ["Learn calculus"],
            outcomes: ["Solve calculus problems"],
        },
    },
    {
        code: "MATH201",
        title: "Linear Algebra",
        lectureHours: 3,
        tutorialHours: 1,
        practicalHours: 0,
        selfStudyHours: 6,
        credits: 3,
        deptCode: "CSE",
        description: {
            objectives: ["Learn linear algebra"],
            outcomes: ["Solve matrix problems"],
        },
    },
    {
        code: "CS102",
        title: "Object Oriented Programming",
        lectureHours: 3,
        tutorialHours: 1,
        practicalHours: 2,
        selfStudyHours: 4,
        credits: 4,
        deptCode: "CSE",
        description: {
            objectives: ["Learn OOP"],
            outcomes: ["Write OOP code"],
        },
    },
    {
        code: "CS202",
        title: "Operating Systems",
        lectureHours: 3,
        tutorialHours: 0,
        practicalHours: 2,
        selfStudyHours: 5,
        credits: 3.5,
        deptCode: "CSE",
        description: {
            objectives: ["Learn OS concepts"],
            outcomes: ["Understand OS internals"],
        },
    },
    {
        code: "CS302",
        title: "Computer Networks",
        lectureHours: 3,
        tutorialHours: 1,
        practicalHours: 2,
        selfStudyHours: 4,
        credits: 4,
        deptCode: "CSE",
        description: {
            objectives: ["Learn networking"],
            outcomes: ["Understand protocols"],
        },
    },
    {
        code: "CS402",
        title: "Software Engineering",
        lectureHours: 3,
        tutorialHours: 1,
        practicalHours: 0,
        selfStudyHours: 6,
        credits: 3,
        deptCode: "CSE",
        description: {
            objectives: ["Learn SE"],
            outcomes: ["Design software systems"],
        },
    },
    {
        code: "EE102",
        title: "Electronics",
        lectureHours: 3,
        tutorialHours: 1,
        practicalHours: 2,
        selfStudyHours: 4,
        credits: 4,
        deptCode: "EE",
        description: {
            objectives: ["Learn electronics"],
            outcomes: ["Design electronic circuits"],
        },
    },
    {
        code: "EE202",
        title: "Signals and Systems",
        lectureHours: 3,
        tutorialHours: 1,
        practicalHours: 0,
        selfStudyHours: 6,
        credits: 3,
        deptCode: "EE",
        description: {
            objectives: ["Learn signals"],
            outcomes: ["Analyze signals"],
        },
    },
    {
        code: "ME102",
        title: "Manufacturing Processes",
        lectureHours: 3,
        tutorialHours: 0,
        practicalHours: 2,
        selfStudyHours: 5,
        credits: 3.5,
        deptCode: "ME",
        description: {
            objectives: ["Learn manufacturing"],
            outcomes: ["Understand processes"],
        },
    },
    {
        code: "ME202",
        title: "Machine Design",
        lectureHours: 3,
        tutorialHours: 1,
        practicalHours: 2,
        selfStudyHours: 4,
        credits: 4,
        deptCode: "ME",
        description: {
            objectives: ["Learn design"],
            outcomes: ["Design machines"],
        },
    },
];

export const prerequisites = [
    { courseCode: "CS201", prerequisiteCode: "CS101" },
    { courseCode: "CS301", prerequisiteCode: "CS201" },
    { courseCode: "CS401", prerequisiteCode: "CS201" },
    { courseCode: "CS501", prerequisiteCode: "CS301" },
    { courseCode: "CS501", prerequisiteCode: "MATH201" },
    { courseCode: "CS202", prerequisiteCode: "CS101" },
    { courseCode: "CS302", prerequisiteCode: "CS201" },
    { courseCode: "CS402", prerequisiteCode: "CS201" },
    { courseCode: "EE201", prerequisiteCode: "EE101" },
    { courseCode: "EE301", prerequisiteCode: "EE201" },
    { courseCode: "EE401", prerequisiteCode: "EE201" },
    { courseCode: "ME201", prerequisiteCode: "ME101" },
    { courseCode: "ME301", prerequisiteCode: "ME101" },
];

export const semesters = [
    {
        year: 2024,
        semester: "EVEN" as const,
        startDate: new Date("2024-08-01"),
        enrollmentDeadline: new Date("2024-08-15"),
        feedbackFormStartDate: new Date("2024-11-15"),
        endDate: new Date("2024-12-15"),
        status: "COMPLETED" as const,
    },
    {
        year: 2025,
        semester: "SUMMER" as const,
        startDate: new Date("2025-01-10"),
        enrollmentDeadline: new Date("2025-01-20"),
        feedbackFormStartDate: new Date("2025-04-20"),
        endDate: new Date("2025-05-20"),
        status: "ONGOING" as const,
    },
    {
        year: 2025,
        semester: "ODD" as const,
        startDate: new Date("2025-08-01"),
        enrollmentDeadline: new Date("2025-08-15"),
        feedbackFormStartDate: new Date("2025-11-15"),
        endDate: new Date("2025-12-15"),
        status: "UPCOMING" as const,
    },
];

export const classrooms = [
    { room: "A101", capacity: 60, type: "LECTURE" as const },
    { room: "A102", capacity: 60, type: "LECTURE" as const },
    { room: "A103", capacity: 40, type: "TUTORIAL" as const },
    { room: "B201", capacity: 50, type: "LECTURE" as const },
    { room: "B202", capacity: 30, type: "LAB" as const },
    { room: "B203", capacity: 30, type: "LAB" as const },
    { room: "C301", capacity: 80, type: "SEMINAR" as const },
    { room: "C302", capacity: 40, type: "TUTORIAL" as const },
    { room: "D101", capacity: 25, type: "LAB" as const },
    { room: "D102", capacity: 60, type: "LECTURE" as const },
];

export const timeSlots = [
    {
        dayOfWeek: "MONDAY" as const,
        sessionType: "THEORY" as const,
        theoryPeriod: "PC-1" as const,
    },
    {
        dayOfWeek: "MONDAY" as const,
        sessionType: "THEORY" as const,
        theoryPeriod: "PC-2" as const,
    },
    {
        dayOfWeek: "MONDAY" as const,
        sessionType: "LAB" as const,
        labPeriod: "LAB-3H-1" as const,
    },
    {
        dayOfWeek: "TUESDAY" as const,
        sessionType: "THEORY" as const,
        theoryPeriod: "PC-3" as const,
    },
    {
        dayOfWeek: "TUESDAY" as const,
        sessionType: "TUTORIAL" as const,
        tutorialPeriod: "T-PC-1" as const,
    },
    {
        dayOfWeek: "WEDNESDAY" as const,
        sessionType: "THEORY" as const,
        theoryPeriod: "PC-4" as const,
    },
    {
        dayOfWeek: "WEDNESDAY" as const,
        sessionType: "THEORY" as const,
        theoryPeriod: "PCPE" as const,
    },
    {
        dayOfWeek: "THURSDAY" as const,
        sessionType: "THEORY" as const,
        theoryPeriod: "HSME" as const,
    },
    {
        dayOfWeek: "THURSDAY" as const,
        sessionType: "LAB" as const,
        labPeriod: "LAB-2H-1" as const,
    },
    {
        dayOfWeek: "FRIDAY" as const,
        sessionType: "THEORY" as const,
        theoryPeriod: "PCDE" as const,
    },
    {
        dayOfWeek: "FRIDAY" as const,
        sessionType: "TUTORIAL" as const,
        tutorialPeriod: "T-PC-2" as const,
    },
];

export const feedbackQuestions = [
    {
        questionText: "The course content was well-organized and clear",
        questionType: "RATING" as const,
        isRequired: true,
        order: 1,
    },
    {
        questionText:
            "The instructor was knowledgeable and explained concepts effectively",
        questionType: "RATING" as const,
        isRequired: true,
        order: 2,
    },
    {
        questionText:
            "The course materials (slides, notes, references) were helpful",
        questionType: "RATING" as const,
        isRequired: true,
        order: 3,
    },
    {
        questionText: "The assignments and projects enhanced my understanding",
        questionType: "RATING" as const,
        isRequired: true,
        order: 4,
    },
    {
        questionText:
            "The instructor was accessible and responsive to questions",
        questionType: "RATING" as const,
        isRequired: true,
        order: 5,
    },
    {
        questionText: "Would you recommend this course to other students?",
        questionType: "YES_NO" as const,
        isRequired: true,
        order: 6,
    },
    {
        questionText: "What did you like most about this course?",
        questionType: "DESCRIPTIVE" as const,
        isRequired: false,
        order: 7,
    },
    {
        questionText: "What improvements would you suggest for this course?",
        questionType: "DESCRIPTIVE" as const,
        isRequired: false,
        order: 8,
    },
    {
        questionText: "The pace of the course was appropriate",
        questionType: "RATING" as const,
        isRequired: true,
        order: 9,
    },
    {
        questionText: "The grading system was fair and transparent",
        questionType: "RATING" as const,
        isRequired: true,
        order: 10,
    },
];

export const courseOfferings2025Spring = [
    {
        courseCode: "CS101",
        instructorEmployeeIds: ["+i1", "+i2"],
        headEmployeeId: "+i1",
        batchYears: [2023],
        programCode: "BTCS",
    },
    {
        courseCode: "CS201",
        instructorEmployeeIds: ["+i2"],
        headEmployeeId: "+i2",
        batchYears: [2022],
        programCode: "BTCS",
    },
    {
        courseCode: "CS301",
        instructorEmployeeIds: ["+i3"],
        headEmployeeId: "+i3",
        batchYears: [2021],
        programCode: "BTCS",
    },
    {
        courseCode: "CS102",
        instructorEmployeeIds: ["+i1"],
        headEmployeeId: "+i1",
        batchYears: [2023],
        programCode: "BTCS",
    },
    {
        courseCode: "CS202",
        instructorEmployeeIds: ["+i2", "+i3"],
        headEmployeeId: "+i2",
        batchYears: [2022],
        programCode: "BTCS",
    },
    {
        courseCode: "EE101",
        instructorEmployeeIds: ["+i4"],
        headEmployeeId: "+i4",
        batchYears: [2023],
        programCode: "BTEE",
    },
    {
        courseCode: "EE201",
        instructorEmployeeIds: ["+i5"],
        headEmployeeId: "+i5",
        batchYears: [2022],
        programCode: "BTEE",
    },
    {
        courseCode: "EE301",
        instructorEmployeeIds: ["+i4"],
        headEmployeeId: "+i4",
        batchYears: [2021],
        programCode: "BTEE",
    },
    {
        courseCode: "ME101",
        instructorEmployeeIds: ["+i6"],
        headEmployeeId: "+i6",
        batchYears: [2023],
        programCode: "BTME",
    },
    {
        courseCode: "ME201",
        instructorEmployeeIds: ["+i7"],
        headEmployeeId: "+i7",
        batchYears: [2022],
        programCode: "BTME",
    },
    {
        courseCode: "MATH101",
        instructorEmployeeIds: ["+i3"],
        headEmployeeId: "+i3",
        batchYears: [2023],
        programCode: "BTCS",
    },
    {
        courseCode: "MATH201",
        instructorEmployeeIds: ["+i2"],
        headEmployeeId: "+i2",
        batchYears: [2022],
        programCode: "BTCS",
    },
];
